### ISSUE TITLE
[Bug]: SDK should support `nullable` type

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#3196]
### Package name

schematics

### Package version

12.2.0

### Reproduction steps

For the following partial specification schema:

```yaml
components:
  schemas:
    Example:
      type: object
      properties:
        field:
         type: string
         nullable: true
```

> [!NOTE]
> Reference to Nullable type on [OAS 3 documentation](https://swagger.io/docs/specification/v3_0/data-models/data-types/#null).

### Current result

```typescript
export interface Example {
  field: string;
}
```

### Expected result

```typescript
export interface Example {
  field: string | null;
}
```

### Additional comments

- [ ] This issue is not limited to `string` type but any type can be `nullable`.
- [ ] The [AnyType](https://swagger.io/docs/specification/v3_0/data-models/data-types/#any-type) should be ignored to avoid `any | null`
